import 'package:e_commerce/core/entities/product_entity.dart';
import 'package:e_commerce/core/utils/assets.dart';
import 'package:e_commerce/core/widgets/fruit_item.dart';
import 'package:flutter/material.dart';

class CustomGridViewFruitsItems extends StatelessWidget {
  const CustomGridViewFruitsItems({super.key, this.productsList});
  final List<ProductEntity>? productsList;
  final List<ProductEntity> productsEntityList = const <ProductEntity>[
    ProductEntity(
      productName: 'apple',
      productImage: Assets.imagesPineapple,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'mango',
      productImage: Assets.imagesMango,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'avocado',
      productImage: Assets.imagesAvocado,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'banana',
      productImage: Assets.imagesBanana,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'pineapple',
      productImage: Assets.imagesPineappleFruit,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'strawberry',
      productImage: Assets.imagesStrawberry,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'watermelon',
      productImage: Assets.imagesWatermelon,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'apple',
      productImage: Assets.imagesPineapple,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'apple',
      productImage: Assets.imagesPineapple,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'apple',
      productImage: Assets.imagesPineapple,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
    ProductEntity(
      productName: 'apple',
      productImage: Assets.imagesPineapple,
      productPrice: 100,
      productDescription: '',
      productCode: '',
      isFeatured: false,
      imageUrl: '',
      expiryMonths: 0,
      isOrganic: false,
      numOfCalories: 0,
      avgRating: 0,
      ratingCount: 0,
      unitAmount: 0,
      reviews: [],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return SliverGrid.builder(
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        mainAxisSpacing: 8,
        crossAxisSpacing: 16,
        childAspectRatio: 163 / 214,
      ),
      itemCount: productsEntityList.length,
      itemBuilder: (context, index) {
        return FruitItem(productEntity: productsEntityList[index]);
      },
    );
  }
}
